
name: CI
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Build and test for macOS
        run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  build-and-test-ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Build and test for iOS
        run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_iOS" -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
